'use strict';
const D=window.ATLAS_DATA,main=document.getElementById('main'),dialog=document.getElementById('course-dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={core:'十大核心课',elective:'专业限选',foundation:'数理基础',practice:'实验与实践'};
const getCourse=id=>D.courses.find(c=>c.id===id),getCase=id=>D.cases.find(c=>c.id===id),getDir=id=>D.directions.find(d=>d.id===id),getSource=id=>D.sources.find(s=>s.id===id);
let state={view:'map',direction:'vision',query:'',group:'all',caseId:''};
const link=(s,label)=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(label||s.title)} ↗</a>`;
const sourceList=ids=>`<ul class="source-list">${ids.map(id=>getSource(id)).filter(Boolean).map(s=>`<li>${link(s)}<p>${esc(s.note)}</p></li>`).join('')}</ul>`;
const badge=c=>`<span class="badge ${c.group}">${groups[c.group]}</span>`;
const chips=arr=>`<div class="tags">${arr.map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</div>`;
const courseButton=c=>`<button data-course="${c.id}">${esc(c.name)}</button>`;
const courseLinks=arr=>`<div class="course-links">${arr.map(courseButton).join('')}</div>`;
const hero=(k,h,p,stats=false)=>`<section class="hero"><div><div class="eyebrow">${k}</div><h1>${h}</h1><p>${p}</p></div>${stats?'<div class="hero-stats"><div class="stat"><b>10</b><span>核心课程模块</span></div><div class="stat"><b>30</b><span>专业限选课程</span></div><div class="stat"><b>09</b><span>真实应用切口</span></div></div>':''}</section>`;
function caseCard(c){return `<a class="case-card" href="#view=cases&case=${c.id}"><span class="company">${esc(c.company)}</span><h3>${esc(c.title)}</h3><p>${esc(c.role)}</p><span class="arrow">课程怎样用在这里 →</span></a>`;}
function courseCard(c){return `<button class="course-card" data-course="${c.id}">${badge(c)}<h3>${esc(c.name)}</h3><p>${esc(c.use)}</p><small>${esc(c.skills.join(' · '))}</small></button>`;}
function directionTabs(){return `<div class="tabs" role="group" aria-label="研究方向">${D.directions.map(d=>`<button data-direction="${d.id}" aria-pressed="${state.direction===d.id}" class="${state.direction===d.id?'active':''}">${esc(d.short)}</button>`).join('')}</div>`;}
function mapView(){const d=getDir(state.direction)||D.directions[2];return hero('COURSE ATLAS / EXPLORE','把课程连起来，看见更多可能。','从十大核心课出发，经过专业限选，走到研究问题、真实工作和你现在就能尝试的小项目。',true)+directionTabs()+`<section class="atlas"><div class="board"><div class="board-heading"><div class="eyebrow">${esc(d.name)}</div><h2>${esc(d.question)}</h2><p>点开任意课程，看看知识在下一步怎样发挥作用。</p></div><div class="map">${d.route.map((col,i)=>`<div class="map-col"><span class="col-label">${['01 / 共同基础','02 / 方法与工具','03 / 深入与实践'][i]}</span>${col.map(id=>{const c=getCourse(id);return `<button class="node" data-course="${id}"><small>${groups[c.group]}</small><strong>${esc(c.name)}</strong></button>`}).join('')}</div>`).join('')}</div><div class="legend">箭头表示内容联系与探索建议，不是官方先修关系；这些课程也可以通往其他方向。</div></div><aside class="research-panel"><div><div class="eyebrow">RESEARCH WINDOW</div><h3>${esc(d.institute)}</h3><p>${esc(d.research)}</p></div><div>${chips(d.topics)}${link(getSource(d.source),'了解官方科研方向')}</div></aside></section><div class="section-head"><div><h2>这些知识，后来用在哪里？</h2><p>先认识具体工作，再决定自己想往哪一步走。</p></div><a href="#view=cases">查看全部 9 个切口 →</a></div><div class="case-grid">${d.cases.slice(0,3).map(id=>caseCard(getCase(id))).join('')}</div><section class="all-core"><h3>共同的起点，是这十门核心课</h3><p>Ⅰ、Ⅱ合并展示，英文与替代课程放在卡片里。配套实验和工具课程仍可在课程全览中查到。</p>${courseLinks(D.courses.filter(c=>c.group==='core'))}</section><div class="notice">培养目录按官网2023目录公开版核对，适用年级请核对本人方案。用途解释与项目建议由本网站整理；完成课程后仍需要项目、工具和专业训练。<a href="#view=sources">查看核对记录</a></div>`;}
function searchbox(label,placeholder){return `<label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" aria-label="${label}" placeholder="${placeholder}" value="${esc(state.query)}"></label>`;}
function courseMatches(){const q=state.query.trim().toLowerCase();return D.courses.filter(c=>(state.group==='all'||c.group===state.group)&&(!q||[c.name,c.use,...c.skills,...c.records.map(r=>r.name+' '+r.code),...c.cases.map(id=>{const x=getCase(id);return [x.company,x.role,x.title].join(' ')})].join(' ').toLowerCase().includes(q)));}
function courseResults(){const cs=courseMatches();return `<div class="result-header"><p class="count" role="status">显示 ${cs.length} 个课程模块 · 展开可查原课程号与各段学分</p>${state.query?'<button class="clear" data-clear>清除搜索</button>':''}</div><div class="course-grid">${cs.map(courseCard).join('')||'<div class="empty">没有找到相关课程。试试“信号”“芯片”“互联网”或课程号。</div>'}</div>`;}
function coursesView(){return hero('COURSE ATLAS / CATALOG','每一门课，都有继续生长的地方。','把上下段和替代选项收进课程模块，同时保留完整课程号、学分与出处。也可以搜企业或工作任务，反过来找课程。')+`<div class="toolbar">${searchbox('搜索课程、课程号或企业','搜索课程、课程号、公司或工作方向')}</div><div class="filters" role="group" aria-label="课程类别">${[['all','全部 · '+D.courses.length],...Object.entries(groups).map(([id,n])=>[id,n+' · '+D.courses.filter(c=>c.group===id).length])].map(([id,n])=>`<button data-group="${id}" class="${state.group===id?'active':''}" aria-pressed="${state.group===id}">${n}</button>`).join('')}</div><div id="results">${courseResults()}</div><div class="notice">网站浏览分类与培养方案的学分分类分别保留。例如Matlab及配套实验属于原方案“专业核心43学分”，但不额外算作一门“十大核心课”。名称有差异的提供材料不擅自认定为同课。<a href="#view=sources">查看全部77条原始目录</a></div>`;}
function caseMatches(){const q=state.query.trim().toLowerCase();return D.cases.filter(c=>!q||[c.title,c.company,c.role,c.task,c.research,c.bridge].join(' ').toLowerCase().includes(q));}
function casesResults(){const cs=caseMatches();return `<p class="count" role="status">${cs.length} 个应用切口</p><div class="case-grid">${cs.map(caseCard).join('')||'<div class="empty">没有找到相关切口。试试“音频”“芯片”或“机器人”。</div>'}</div>`;}
function casesView(){if(state.caseId&&getCase(state.caseId))return caseView(getCase(state.caseId));return hero('COURSE ATLAS / BEYOND THE CLASSROOM','学过这些，未来可以做什么？','可以走向宏大的科研问题，也可以先从一段噪声、一处芯片错误、一条不稳定的连接开始。')+`<div class="toolbar">${searchbox('搜索应用与企业','搜索企业、工作任务或研究问题')}</div><div id="results">${casesResults()}</div><div class="notice">企业例子来自官方产品、技术文档或招聘职责样本。岗位名称与任务拆解用于认识工作，不表示企业当前在招，也不表示某门课能直接换来某个岗位。</div>`;}
function caseView(c){const related=D.courses.filter(x=>x.cases.includes(c.id));return `<a class="back" href="#view=cases">← 返回全部应用切口</a><div class="case-title"><div class="eyebrow">${esc(c.company)}</div><h1>${esc(c.title)}</h1><p>${esc(c.role)}</p></div><div class="content-grid"><div><section class="paper"><div class="eyebrow">01 / 真实应用</div><h2>这里真的在解决什么问题</h2><p>${esc(c.fact)}</p><h3>如果参与这类工作</h3><p>${esc(c.task)}</p><h3>课程知识怎样接上它</h3><p>${esc(c.bridge)}</p>${courseLinks(related)}<p class="fineprint">课程按钮可以查看各自的具体贡献。以下联系是编辑分析，不是企业或院系给出的官方选课清单。</p></section><section class="paper"><div class="eyebrow">02 / 继续深入</div><h2>也可以把它变成研究问题</h2><p>${esc(c.research)}</p>${sourceList(c.directions.map(id=>getDir(id).source))}<h3>距离真正参与，还需要什么</h3><p>${esc(c.gap)}</p></section></div><aside><section class="paper project"><div class="eyebrow">START SMALL</div><h2>先做一件小事</h2><span class="step-label">试着做</span><p>${esc(c.project)}</p><span class="step-label">留下可展示的结果</span><p>${esc(c.deliverable)}</p><p class="fineprint">这是自选探索建议，不是课程官方作业，也不要求先购买硬件。</p></section><section class="paper"><h2>依据与边界</h2>${sourceList(c.sources)}<p class="fineprint">核对日期：${D.updated}。产品事实来自官方页面；任务拆解、课程关系、研究延伸和练习由本站整理。</p></section></aside></div>`;}
function catalogRows(){const q=state.query.trim().toLowerCase();const rows=D.catalog.filter(c=>!q||[c.name,c.code,c.group].join(' ').toLowerCase().includes(q));return `<p class="count" role="status">原始目录显示 ${rows.length} / 77 条 · 含中英文、上下段及替代选项</p><div class="tablewrap"><table><thead><tr><th>课程 / 课程号</th><th>原方案类别</th><th>学分</th><th>选项与来源页</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.name)}<small>${c.code}</small></td><td>${esc(c.group)}</td><td>${c.credits}</td><td>${esc(c.choiceRule|| (c.starred?'标星实验课':'详见原方案'))}<small>PDF 第${c.sourcePage}页</small></td></tr>`).join('')||'<tr><td colspan="4">没有找到相关目录条目。</td></tr>'}</tbody></table></div>`;}
function sourcesView(){return hero('COURSE ATLAS / EVIDENCE','好用的地图，也要看得清依据。','以下把已核对的培养要求、尚待确认的版本问题与我们的解释分开。核对日期：2026年9月30日。')+`<div class="summary-grid"><article><b>10</b><p>核心课程模块<br>上下段不重复计门数</p></article><article><b>77</b><p>专业教育目录条目<br>含替代课与英文选项</p></article><article><b>156</b><p>公开版基本总学分<br>不是全目录累加值</p></article><article><b>2023</b><p>官网目录版本<br>不冒充最新适用方案</p></article></div><section class="paper"><h2>本次核对使用什么版本</h2><p>完整课程目录依据清华官网2023目录中的电子信息科学与技术专业培养方案。重新检索了院系本科教学、2024与2025相关培养信息、课程建设报道；尚未取得可确认适用于2024—2026级的完整公开方案。2024年招生介绍与因材施教项目只补充培养理念与方向，不能据此改写学分要求。</p>${sourceList(['plan','core','intro2024','training'])}<p class="fineprint">网站面向各年级认识课程与去向；个人修读、免修、替代、毕业与选课决策，请核对本人教学门户及当年通知。</p></section><div class="section-head"><div><h2>逐项核对记录</h2><p>“十大核心课”是课程体系口径，“专业核心43学分”是方案学分口径。</p></div></div><div class="audit">${D.audit.map(([s,t,p])=>`<article><div class="status ${s==='待核对'?'pending':''}">${s}</div><h3>${esc(t)}</h3><p>${esc(p)}</p></article>`).join('')}</div><section class="all-core"><h3>十大核心课 · 合并方式</h3>${courseLinks(D.courses.filter(c=>c.group==='core'))}<p>分段课程合并为一张卡；三选一等选项放在同一知识模块，但不合并课程身份与学分。工具、实验与实践环节保留独立说明。</p></section><div class="section-head"><h2>完整专业课程目录</h2><a href="catalog.json" download>下载结构化数据 ↓</a></div><div class="toolbar">${searchbox('搜索原始培养目录','搜索原始名称、课程号或分组')}</div><div id="results">${catalogRows()}</div><div class="section-head"><h2>通识教育同样有价值</h2></div><div class="general-grid">${D.general.map(c=>`<article><h3>${esc(c.name)}</h3><p>${esc(c.role)}</p></article>`).join('')}</div><p class="fineprint">展示通识体系与能力价值，不穷尽每学期动态开设的通识选修课程；完整要求见官方PDF第5—7页。</p><div class="section-head"><h2>应用与研究资料</h2></div><div class="source-cols"><section class="paper"><h3>企业官方资料</h3>${sourceList(D.cases.flatMap(c=>c.sources))}</section><section class="paper"><h3>院系科研介绍</h3>${sourceList(D.directions.map(d=>d.source))}<p class="fineprint">课程简介还参考了项目提供的核心课、限选课材料；公开网站不附个人文件，不把未确认版本的大纲称为现行大纲。完整原文请以教务发布为准。</p></section></div>`;}
function bindCourses(root){root.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>openCourse(b.dataset.course));}
function openCourse(id){const c=getCourse(id);if(!c)return;document.getElementById('dialog-content').innerHTML=`<div class="dialog-header">${badge(c)}<button id="close-dialog" aria-label="关闭课程详情">关闭 ×</button></div><article class="dialog-body"><div class="eyebrow">COURSE / CONNECTIONS</div><h2 id="dialog-title">${esc(c.name)}</h2><p>${esc(c.use)}</p>${chips(c.skills)}${c.note?`<p class="module-note">${esc(c.note)}</p>`:''}<h3>学过以后，可以在哪些地方接着用</h3><div class="case-grid">${c.cases.map(id=>caseCard(getCase(id))).join('')}</div><h3>现在就能试的小切口</h3><p>${esc(c.mini)}</p><p class="fineprint">自选探索建议，非官方课程作业。${esc(c.knowledgeStatus)}</p><h3>原课程条目 · 合并展示，保留区别</h3><div class="tablewrap"><table><thead><tr><th>课程名称 / 课程号</th><th>学分</th><th>原方案分类</th></tr></thead><tbody>${c.records.map(r=>`<tr><td>${esc(r.name)}<small>${r.code}</small></td><td>${r.credits}</td><td>${esc(r.group)}</td></tr>`).join('')}</tbody></table></div><p class="fineprint">选项不能全部相加。${link(getSource('plan'),'核对官方方案')} · PDF第${[...new Set(c.records.map(r=>r.sourcePage))].join('、')}页。</p>${c.prerequisites?`<h3>提供材料中的先修说明</h3><p>${esc(c.prerequisites)}</p><p class="fineprint">${c.prerequisiteStatus}</p>`:''}<h3>继续接近真实工作</h3><p>点开上面的应用切口，查看工作任务、科研问题、可交付的小项目和待补能力。上完课程是起点，具体方向还需要工具、项目和专业训练。</p></article>`;document.getElementById('close-dialog').onclick=()=>dialog.close();dialog.querySelectorAll('.case-card').forEach(a=>a.onclick=()=>dialog.close());if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
function updateResults(){document.getElementById('results').innerHTML=state.view==='courses'?courseResults():state.view==='sources'?catalogRows():casesResults();bindCourses(main);main.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{state.query='';document.getElementById('search').value='';updateResults()});}
function render(){document.querySelectorAll('[data-view]').forEach(a=>{a.classList.toggle('active',a.dataset.view===state.view);if(a.dataset.view===state.view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});main.innerHTML=state.view==='courses'?coursesView():state.view==='cases'?casesView():state.view==='sources'?sourcesView():mapView();bindCourses(main);main.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>{state.direction=b.dataset.direction;history.replaceState(null,'','#view=map&direction='+state.direction);render()});main.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{state.group=b.dataset.group;render()});const s=document.getElementById('search');if(s)s.oninput=()=>{state.query=s.value;updateResults()};document.title=(state.caseId&&getCase(state.caseId)?getCase(state.caseId).title+' · ':'')+'课程去向地图 · 清华电子本科探索';}
function navigate(){if(location.hash==='#main')return;const p=new URLSearchParams(location.hash.slice(1));state.view=['map','courses','cases','sources'].includes(p.get('view'))?p.get('view'):'map';state.direction=getDir(p.get('direction'))?p.get('direction'):'vision';state.caseId=getCase(p.get('case'))?p.get('case'):'';state.query='';state.group='all';if(dialog.open)dialog.close();render();window.scrollTo({top:0});if(p.has('course'))openCourse(p.get('course'));}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('hashchange',navigate);navigate();
