'use strict';
const opportunities=[
 {id:'mentor',name:'新生导师与方向见面会',stage:'discover',fit:'还不清楚专业里有哪些方向，想先找到可以交流的人。',fact:'电子系微纳光子学实验室2025级活动报道介绍了新生导师计划，并记录了方向报告和实验室参观。',prepare:'准备两个具体问题：这类研究日常做什么？我现在可以通过什么课或小任务了解它？',entry:'关注所在班级、院系及实验室的导师交流与讲座通知，先确认活动面向的对象。',scope:'活动实例，不表示每个实验室随时开放参观；安排以本年通知为准。',url:'https://nano-oelab.ee.tsinghua.edu.cn/Home/xxfb/xxfb_1.html?id=870',title:'实验室官方 · 2025级导师见面会（2025-11）'},
 {id:'srt',name:'SRT · 大学生研究训练',stage:'try',fit:'有一个好奇的问题，希望在指导下经历一次研究过程。',fact:'SRT是清华本科生研究训练的重要形式，强调通过研究实践培养探索与创新能力。电子系实验教学中心也将SRT列为研究训练载体。',prepare:'整理兴趣、已学课程、每周可投入时间和一份小尝试记录，再与指导教师讨论可承担的任务。',entry:'先阅读项目介绍；向电子系本科教学渠道或意向指导教师询问本学期SRT项目、报名和立项通知。',scope:'这里不是报名系统。未核验到2026年秋季完整公开项目清单与报名截止时间；具体资格、学分及流程以教务通知为准。',url:'https://www.tsinghua.edu.cn/info/1181/52881.htm',title:'清华官方 · SRT计划介绍（2014，机制背景）',extra:'https://www.ee.tsinghua.edu.cn/info/1016/1014.htm',extraTitle:'电子系实验教学中心 · 研究训练介绍'},
 {id:'lab-course',name:'实验课与综合设计实践',stage:'try',fit:'更想从有边界的动手任务开始，体验实现、调试和协作。',fact:'电子系实验教学中心将基础实验、综合设计与研究创新相衔接，覆盖软硬件多类实践。',prepare:'从课程图中选一个相关实验或综合实践，先检查先修基础、课时负担和本人的修读要求。',entry:'在课程全览查看实验与实践模块，再通过本人教学门户核对当期开课与选课条件。',scope:'课程目录与实际开课是两件事；不要把网页上的所有实践课程同时加入课表。',url:'https://www.ee.tsinghua.edu.cn/info/1016/1014.htm',title:'电子系官方 · 实验教学中心',courseLink:true},
 {id:'qihang',name:'电子系启航计划',stage:'try',fit:'希望系统训练科研科创能力，并在项目推进中得到支持。',fact:'电子系2026年科研科创介绍将启航计划列为人才培养项目，涉及科研基础训练与项目推进。',prepare:'把想做的题目缩成一个可验证的问题，说明现有基础、可能的方法和希望获得的指导。',entry:'通过电子系学生科创与培养通知查当期招募；带探索卡了解项目主题和培养安排。',scope:'参加对象、选拔和时间安排须按当期通知核对，网站不代为判定资格。',url:'https://www.ee.tsinghua.edu.cn/info/1439/4298.htm',title:'电子系官方 · 科研科创（2026-04）'},
 {id:'tailored',name:'电子系因材施教特色培养',stage:'deepen',fit:'已通过课程或项目形成较明确的方向，希望持续投入。',fact:'院系公开介绍列出光电子、AI+系统、集成电路、未来通信等方向，结合导师指导、课程和实践；2025年活动报道仍可见相关培养安排。',prepare:'比较公开方向，写明最想研究的问题、已有尝试与可投入时间，再讨论导师和项目是否适合。',entry:'阅读方向介绍，关注院系当期申请与动态选拔通知；与老师交流双向选择的条件。',scope:'2023年介绍用于理解培养机制，不照搬旧名额、招生时点或奖励条件。',url:'https://www.ee.tsinghua.edu.cn/info/1076/3981.htm',title:'电子系官方 · 因材施教项目介绍（2023）',extra:'https://nano-oelab.ee.tsinghua.edu.cn/Home/xxfb/xxfb_1.html?id=870',extraTitle:'2025级项目导师见面会'},
 {id:'competition',name:'科创赛事与挑战杯',stage:'try',fit:'想通过团队任务、作品和展示获得一次完整的工程或科研体验。',fact:'电子系公开列有硬件、软件、电子设计、AI、无人机等赛事；2026年挑战杯报道展示了研究与作品类项目。',prepare:'先看任务和分工是否符合兴趣，再确定一个能完成并评价的版本；保留过程、测试和复现记录。',entry:'从院系科创介绍了解赛事，再查当届通知中的赛道、组队、时间与参赛规则。',scope:'竞赛是体验与反馈的方式之一，获奖不是判断适合某方向的唯一尺度。',url:'https://www.ee.tsinghua.edu.cn/info/1439/4298.htm',title:'电子系官方 · 科创赛事介绍',extra:'https://www.ee.tsinghua.edu.cn/info/1076/5199.htm',extraTitle:'2026年校挑战杯项目报道'},
 {id:'spark',name:'星火计划与跨学科学术交流',stage:'deepen',fit:'已有学术兴趣，希望接触跨专业问题、同行交流和研究训练。',fact:'校团委介绍的星火计划面向具有学术志趣的学生，提供讲座、讨论、项目与调研等培养环节。',prepare:'带着自己的问题与一份已有作品，说明为什么需要跨专业交流，以及希望补充什么视角。',entry:'从校团委项目介绍了解机制，关注当期选拔通知，再判断投入和要求是否合适。',scope:'这是有选拔要求的培养项目，不是报名即获得全部资源。',url:'https://www.tsinghua.edu.cn/xtw/info/1013/1107.htm',title:'清华校团委 · 因材施教培养计划'},
 {id:'embodied-course',name:'新近教学动态 · 具身智能综合系统实验',stage:'deepen',fit:'对机器人感知、软件与硬件协同感兴趣，并已有相关基础。',fact:'电子系2026年9月14日报道与智元共建教学实验室，介绍《具身智能综合系统实验》计划于2026年秋季面向本科高年级开课。',prepare:'先检查编程、感知、系统实践基础，再向教学渠道核对课程号、先修条件和实际选课安排。',entry:'从官方教学新闻了解内容，通过教学门户确认开课与余量。',scope:'作为新课程线索单列，尚未取得完整教学大纲与课程目录记录，不加入2023目录的学分统计。',url:'https://www.ee.tsinghua.edu.cn/info/1076/5393.htm',title:'电子系官方 · 具身智能教学实验室（2026-09）'}
];
const opportunityStages={all:'全部入口',discover:'先认识方向',try:'动手试一试',deepen:'持续深入'};
function opportunitiesView(){const stage=state.stage||'all';const list=opportunities.filter(p=>stage==='all'||p.stage===stage);return hero('OPPORTUNITIES / 培养与实践','方向看见了，下一步在哪里试？','把课程之外的培养资源也接进来。按自己当前的问题选择一次合适的尝试，不必把所有项目都参加一遍。')+`<div class="filters opportunity-filters" aria-label="按探索阶段筛选">${Object.entries(opportunityStages).map(([id,label])=>`<a href="#view=opportunities&stage=${id}" class="${stage===id?'active':''}" ${stage===id?'aria-current="true"':''}>${label}</a>`).join('')}</div><p class="count">${list.length}个培养与实践入口 · 公开信息核对：2026-10-01</p><div class="opportunity-grid">${list.map(p=>`<article class="paper opportunity-card"><div class="eyebrow">${opportunityStages[p.stage]}</div><h2>${esc(p.name)}</h2><p class="opportunity-fit">想解决的问题：${esc(p.fit)}</p><h3>公开信息</h3><p>${esc(p.fact)}</p><h3>现在可以怎样开始</h3><p>${esc(p.entry)}</p><h3>带着什么去</h3><p>${esc(p.prepare)}</p><div class="teacher-links">${link({url:p.url,title:p.title})}${p.extra?link({url:p.extra,title:p.extraTitle}):''}${p.courseLink?'<a href="#view=courses">查看课程与实践模块 →</a>':''}</div><p class="fineprint">${esc(p.scope)}</p><a class="action-link" href="#view=explore&opportunity=${p.id}">为这次探索做准备 →</a></article>`).join('')}</div><div class="notice">“想解决的问题”和准备建议为本站整理；项目事实来自所附官方来源。培养机会会更新，页面不是招募公告或报名平台。基础课程、通识学习和自由探索同样重要，不需要先确定职业才能认真学习。</div>`;}
